complete contact page
Suvradippaul/Responsive-web-design pull request #3
Opened 2022-10-11 10:23 UTC by Ritu-03Thakur

changes -:
1. Index.html
2. style.css
3. add photos
![contact_page1](https://user-images.githubusercontent.com/105920415/195065635-9908b4f0-3953-445c-b244-d4cbf8a4fa10.png)

2022-10-11 11:12 UTC, Suvradippaul commented
Hey @Ritu-03Thakur, I have created a new branch 'test'. Please give PRs to that branch. I need to check few things before merging to 'main' branch.

2022-10-15 13:02 UTC, Suvradippaul requested changes

2022-10-15 13:02 UTC, Suvradippaul commented on style.css
> +/* Contact US */
Please make it responsive

2022-10-15 13:02 UTC, Suvradippaul commented on style.css
> +    background-color: rgb(65, 1, 1);
Please maintain the color theme

2022-10-20 05:52 UTC, Suvradippaul commented
@Ritu-03Thakur Its conflicting

2022-10-20 08:34 UTC, Ritu-03Thakur commented
Should I make another pull request to main branch?

On Thu, 20 Oct, 2022, 11:23 am Suvradip Paul, ***@***.***>
wrote:

> @Ritu-03Thakur <https://github.com/Ritu-03Thakur> Its conflicting
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Suvradippaul/Responsive-web-design/pull/3#issuecomment-1284976945>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZIDPH4M3KZ27N4BG3UMJJTWEDM3NANCNFSM6AAAAAARCEIBR4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-20 11:07 UTC, Suvradippaul commented
> Should I make another pull request to main branch?

Yes

2022-10-20 13:26 UTC, closed without merging